### ISSUE TITLE
WebhookCall::create fails - unexpected ')'

### ISSUE THREAD

**Issue by annieneel** [jmsfwk/lumen-webhook-server#1]
It looks like Spatie updated the underlying web hook package and anything that implements the abstract class `WebhookCallEvent` is missing an errorType and errorMessage. 

Depending on how you want to handle it - it seems pretty straightforward to add:

`    /** @var string */
    public $errorType = null;
  /** @var string */
    public $errorMessage = null;`

to variable declarations 

` $this->errorMessage = $exception->getMessage();
            $this->errorType = get_class($exception);`

to the catch, and update the dispatchEvent to

`   event(new $eventClass(
            $this->httpVerb,
            $this->webhookUrl,
            $this->payload,
            $this->headers,
            $this->meta,
            $this->tags,
            $this->attempts(),
            $this->response,
            $this->errorType,
            $this->errorMessage
        ));`

From first glance this seems to be the only thing broken with the update, super minor! If you're short on time I can fork and submit a PR, but this may not be what you have in mind.

**Comment by jmsfwk** [comment]
Fixed by #2
